steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Deploy to App Engine
  - name: 'gcr.io/google-appengine/deploy'
    args: ['app.yaml']

# Specify the App Engine environment
timeout: '900s'
